apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
  labels:
    app.kubernetes.io/name: gitea
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: guardian-gp3
  resources:
    requests:
      storage: 2Gi
